version: '3.3'

services:
  # NATS Messaging
  nats:
    image: nats:2.10
    container_name: WhoWillAnswer_nats
    ports:
      - "4222:4222"
      - "8222:8222"  # Optional: NATS monitoring port
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3
