version: '3.3'

services:
  # NATS Messaging
  nats:
    image: nats:2.10
    container_name: WhoWillAnswer_nats
    ports:
      - "4222:4222"
      - "8222:8222"  # Optional: NATS monitoring port
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: